### ISSUE TITLE
Package Seq.App.HttpRequest could not be interrogated for app configuration

### ISSUE THREAD

**Issue by makhsudov-mz** [datalust/seq-app-httprequest#11]
Could not install app
Package Seq.App.HttpRequest could not be interrogated for app configuration: no type marked with `[SeqApp]` could be found.

I cannot install the package in Seq 4.2.1113. what is the problem or the package does not support this version of seq

**Comment by liammclennan** [comment]
@makhsudov-mz yes, that is likely to be the problem. Seq.App.HttpRequest did not exist in the Seq 4.2 timeframe.

**Comment by makhsudov-mz** [comment]
thanks for the answer
