### ISSUE TITLE
How to search/reference log entry/event by Id

### ISSUE THREAD

**Issue by rj-au** [datalust/seq-app-httprequest#18]
I would like to use Id property the log event to generate a URL to send to a 3rd party system.

But I'm a little confused with the terminology and the data:

If click on "Just find this" I get a search query like `@Id = 'event-47cb9d000e7408dd1328485600000000'`
![image](https://github.com/user-attachments/assets/36c9765b-6654-464e-ba61-b33b74d604a5)

Problem is, I can't seem to get this field

---

Then I copy "Download RAW JSON: I get:
```json
{
  "@t": "2024-11-26T23:44:34.0000000Z",
  "@mt": "Sent Standby status message at 442/FAA58670",
  "@m": "Sent Standby status message at 442/FAA58670",
  "@i": "1c61adeb",
  "@l": "DEBUG",
  "APP_NAME": "XXXXXX",
  "ENVIRONMENT": "development"
}
```
The `@i` field looks like what I'm after since this doco describes it as `event id; a 32-bit numeric hash of the event's message template`:
https://github.com/serilog/serilog-expressions/?tab=readme-ov-file#language-reference

They are obviously not the same, but I can't seem to get a query to work for `@i`

When I send `@i` to a webhook, it is no longer HEX, but decimal, i.e `3147220028`

The confusion is around `@Id` (Event Id) and `@i` (event id) - both have the same name.

**Comment by rj-au** [comment]
Looks like `@Id` is available to the Body Template, but just was not documented either here
https://docs.datalust.co/docs/template-syntax or here https://github.com/serilog/serilog-expressions/?tab=readme-ov-file#language-reference

I should be able to create a URL from that then
```text
https://seq.xxxx.io/#/events?range=1d&signal=signal-m33301,signal-274,signal-30&filter=@Id%20%3D%20'event-MY_EVENT_ID'
```

**Comment by liammclennan** [comment]
Hi Richard, 

The CLEF properties are documented [here](https://docs.datalust.co/docs/posting-raw-events#the-clef-format) and the Seq built-in properties are documented [here](https://docs.datalust.co/docs/built-in-properties-and-functions).

Within a message template  you can use either. 

I'm not sure why `@i` is called Event id, when it is actually the event type (`@EventType` in Seq). Many events may have the same `@i` value.

**Comment by rj-au** [comment]
Thanks @liammclennan, this is what I was after
https://docs.datalust.co/docs/built-in-properties-and-functions
