### ISSUE TITLE
Trouble with substitutions inside templated JSON

### ISSUE THREAD

**Issue by software-programmer** [datalust/seq-app-httprequest#5]
Should we be able to substitute inside a JSON template using expressions / directives?

e.g.

`
{ {
  'rawTime': @t,
  'formattedTime': 'The time is {@t:HH:mm:ss}'
} }
 `

outputs

`
{
  "rawTime": "2022-01-05T16:29:09.7599190+00:00",
  "formattedTime": "The time is {@t:HH:mm:ss}"
}
`

I can't seem to find any relevant documentation as to how I might "escape" out of the JSON to indicate a substitution is required when trying to perform interpolation

**Comment by software-programmer** [comment]
I worked it out - seems the trick is to not use an outer template marker for JSON, and escape the JSON brackets manually

`
{{ 
"rawTime": "{@t}", 
"formattedTime": "The time is {@t:HH:mm:ss}" 
}}
`

**Comment by nblumhardt** [comment]
:+1: thanks for the follow-up, Matt.

I think:

```
{ { 'rawTime': @t, 'formattedTime': concat('The time is ', tostring(@t, 'HH:mm:ss')) } }
```

will also do it (preferable, if you're doing any more complex JSON construction).

HTH!
