### ISSUE TITLE
Error while installing the app. The command failed: 'Syntax' property specified was not found.

### ISSUE THREAD

**Issue by incoventures** [datalust/seq-app-httprequest#6]
I am getting the following error when i try install Seq.App.HttpRequest with the default settings
```
Could not install app
Package Seq.App.HttpRequest could not be interrogated for app configuration: The command failed: 'Syntax' property specified was not found.
```

**Comment by nblumhardt** [comment]
Hi Igor, thanks for your message. _Seq.App.HttpRequest_ uses [a new app feature added in Seq 2021.4](https://github.com/datalust/seq-tickets/issues/1413) - you'll need to update your Seq version, in order to install it.

Hope this helps,
Nick

**Comment by incoventures** [comment]
Thank you, Nick. it works now!
