### ISSUE TITLE
Authentication failing with Twilio

### ISSUE THREAD

**Issue by kampagnol** [datalust/seq-app-httprequest#7]
Outbound HTTP request failed with status code Unauthorized

tried using <SID>:<Token> in Authentication Header
tried also using base64 encoded version of <SID>:<Token> in Authentication Header

same response

What am I missing?

**Comment by liammclennan** [comment]
Hi @kampagnol ,

You might find an answer in [this post I wrote about connecting seq-app-httprequest to Twilio](https://blog.datalust.co/httprequest-webhook/). 

If not, the trick will be to solve the Twilio authentication problem first, with cURL or Postman etc, then copy it over to the Seq app.

**Comment by kampagnol** [comment]
I indeed was following that document. And I also had your same idea - cURL is working just fine.

I get to see the request by using curl -vvv and from this line:

`Authorization: Basic QZDMzODczMzEwNGQ3Ng==`

...I copied the `QZDMzODczMzEwNGQ3Ng==` to the "Authentication Header" field in the app instance.

(string is obviously changed)

It still fails. So I'm not sure how to proceed at this stage.

What am I missing?!?

**Comment by liammclennan** [comment]
You need to put the whole thing (Authorization: Basic QZDMzODczMzEwNGQ3Ng==) in the form field.

**Comment by kampagnol** [comment]
Progress!

Now I get Outbound `HTTP request failed with status code BadRequest`

In the "Body" text box I have put:

`To=%2B35699775522&
MessagingServiceSid=MG89d49dc49dc344c344c49dc344c5a52e&
Body=Testing SMS`

...with a carriage return at the end of the first 2 lines.

Twilio logs and errors show absolutely nothing.

Ideas?

**Comment by nblumhardt** [comment]
I don't think a carriage return will be valid between `&` and `Body=`.

**Comment by nblumhardt** [comment]
Hoping you were able to figure this one out; closing as stale, but please feel free to chime in/reopen if any more help's needed here.
