### ISSUE TITLE
Zoom webhooks: " Outbound HTTP request failed with status code BadRequest"

### ISSUE THREAD

**Issue by richard-stafflink** [datalust/seq-app-httprequest#8]
I've installed the following app: `HTTP 1.0.0-dev-00016 by Datalust...`

Added an instance (_REMOVED_PART indicates part of the secret has been removed for posting here):
```
{
  "Url": "https://inbots.zoom.us/incoming/hook/XIuu0_REMOVED_PART",
  "Method": "POST",
  "Body": "",
  "BodyIsTemplate": "False",
  "MediaType": "application/json",
  "AuthenticationHeader": "",
  "OtherHeaders": "Authorization: dZH7ayu8_REMOVED_PART",
  "ExtendedErrorDiagnostics": "False"
}
```

The error I get is:
```
{"@t":"2022-11-15T00:45:22.6578637Z","@mt":"Outbound HTTP request failed with status code {StatusCode}","@m":"Outbound HTTP request failed with status code BadRequest","@i":"93101f49","@l":"Error","StatusCode":"BadRequest","AppId":"hostedapp-69","AppInstanceId":"appinstance-71"}
```

I've also tried this, but got the same error:
```
...
  "Body": "test",
  "BodyIsTemplate": "true",
...
```

I've proven the webhook works by run this locally:
```
curl 'https://inbots.zoom.us/incoming/hook/XIuu04_REMOVED_PART' -X POST -H 'Authorization: dZH7ayu_REMOVED_PART' -d 'Hello World!'
```

![image](https://user-images.githubusercontent.com/106497642/201799224-5c8070c0-6c01-402a-8a22-3f0a87445538.png)

**Comment by richard-stafflink** [comment]
I'm now testing with: https://webhook.site/#!/56e4c909-2dce-4208-b1d4-13774bde09b9/6338fbc9-3445-4745-9ef9-e5b43cc5c72b/1

If I also add the `Content-Type` header:
```
...
"OtherHeaders": "Authorization: xxx\nContent-Type: application/json",
...
```

I get this error:
```
System.InvalidOperationException: Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
   at Seq.App.HttpRequest.HttpRequestMessageFactory.FromEvent(LogEvent evt) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpRequestMessageFactory.cs:line 62
   at Seq.App.HttpRequest.HttpApp.OnAsync(Event`1 evt) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpApp.cs:line 84
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 121
```

**Comment by richard-stafflink** [comment]
The requests are getting through to the webhook test site, but there is no body.
How do I configure the webhook instance to pass the log entry details?

![image](https://user-images.githubusercontent.com/106497642/201804475-3c443d1b-9731-437f-9c89-952036c976b1.png)

**Comment by richard-stafflink** [comment]
Ok, got it working:

```
{
  "Url": "https://inbots.zoom.us/incoming/hook/XXXXXXXXXX",
  "Method": "POST",
  "Body": "{@m}",
  "BodyIsTemplate": "True",
  "MediaType": "text/html",
  "AuthenticationHeader": "",
  "OtherHeaders": "Authorization: XXXXXXXX",
  "ExtendedErrorDiagnostics": "False"
}
```

**Comment by nblumhardt** [comment]
Hi Richard,

To guarantee that the body is valid JSON no matter the content of `@m`, you can use an object literal:

```
{ {
   Url: 'https://inbots.zoom.us/incoming/hook/XXXXXXXXXX',
   Method: 'POST',
   Body: @m,
   BodyIsTemplate: 'True',
   MediaType: 'text/html',
   AuthenticationHeader: '',
   OtherHeaders: 'Authorization: XXXXXXXX',
   ExtendedErrorDiagnostics: 'False'
} }
```

Hope this helps,
Nick

**Comment by richard-stafflink** [comment]
@nblumhardt That code snippet doesn't seem to work - I copied it as is, and also tried removing the extra squiggly brackets.
Keeps erroring with "Syntax error ..."

**Comment by richard-stafflink** [comment]
```
{
  "Url": "https://webhook.site/56e4c909-2dce-4208-b1d4-13774bde09b9",
  "Method": "POST",
  "Body": "{{ message: \"{message}\" }}",
  "BodyIsTemplate": "True",
  "MediaType": "application/json",
  "AuthenticationHeader": "",
  "OtherHeaders": "Authorization: xxxxxx",
  "ExtendedErrorDiagnostics": "False"
}
```

Produces:
Raw Content: `{ message: "" }`

**Comment by nblumhardt** [comment]
I might have typo'd something I can't spot - the version with the extra squiggly brackets is the one, I think.

Where is the syntax error message being raised? (At the API, or locally in the Seq app?)

I'll have a tinker with the app here now and see if I can spot it.

**Comment by nblumhardt** [comment]
Ah sorry, I see now :-) you posted the app settings, while I thought you were posting the "Body" field. Looks like your original solution is the one to go with.

**Comment by richard-stafflink** [comment]
@nblumhardt could you share an example where a JSON body (including the time and message) is sent to: `https://webhook.site/56e4c909-2dce-4208-b1d4-13774bde09b9`?

**Comment by richard-stafflink** [comment]
This App instance JSON:
```
{
  "Url": "https://inbots.zoom.us/incoming/hook/XXXXXX",
  "Method": "POST",
  "Body": "{ { @m, @t } }",
  "BodyIsTemplate": "True",
  "MediaType": "text/html",
  "AuthenticationHeader": "",
  "OtherHeaders": "Authorization: XXXX",
  "ExtendedErrorDiagnostics": "False"
}
```

Sends this on Zoom:
![image](https://user-images.githubusercontent.com/106497642/201820534-16b4a802-3fcc-40fb-a645-b76df778dfce.png)

But if I change `"MediaType": "application/json"` then I get a "bad request" error.

BTW, I would be using something other than Zoom chat if I had a choice.

**Comment by nblumhardt** [comment]
To pass arbitrary JSON, it looks like you'd need to add `?format=list` to the webhook URL:

https://support.zoom.us/hc/en-us/articles/4418193782029-Using-Zoom-s-Incoming-Webhook-Chatbot

My guess is that without the format specified, it'll be attempting to parse the body in something like this format:

https://marketplace.zoom.us/docs/guides/chatbots/customizing-messages/message-with-header/

Not super-familiar with Zoom chat though, unfortunately - I hope this helps!

**Comment by richard-stafflink** [comment]
I can't get much more than text/html working, so I'll just have to settle with that for now.

**Comment by richard-stafflink** [comment]
I was able to get a little further with formatted message, here's the config I used:

```
{
  "Url": "https://inbots.zoom.us/incoming/hook/XXXXXXXX?format=full",
  "Method": "POST",
  "Body": "{ {\n  head: {\n    text: @l\n  },\n  body: [\n    {\n      type: 'message',\n      text: @m\n    },\n    {\n      type: 'message',\n      text: @t\n    },\n    {\n      type: 'message',\n      text: 'All PROD logs',\n      link: 'https://seq.stafflink.io/#/events?signal=(signal-m33301~signal-50),signal-30'\n    }\n  ]\n} }",
  "BodyIsTemplate": "True",
  "MediaType": "application/json",
  "AuthenticationHeader": "[seq-preserve]",
  "OtherHeaders": "",
  "ExtendedErrorDiagnostics": "False"
}
```

**Comment by richard-stafflink** [comment]
@nblumhardt @liammclennan is there a way of creating a link (perma?) back to a specific log event using the `@i` property?
If not, how would I construct a URL using the log entry data at hand?

**Comment by nblumhardt** [comment]
Hi Richard! The event carries a string `@seqid` property that is the event's Seq-style identifier, e.g. `event-123456`.

Right now, there's no way to automatically format this into a link back to the Seq instance (it'd be awesome if we could plug in some custom functions via the template `NameResolver` to support things like `link()`) but you can emulate it with:

```sql
concat('https://seq.example.com/#/events?filter=@Id %3D ''', @seqid, '''')
```

The escaping of those `'` quotes is a bit painful 😬 ... let me know if this does the trick for you!

**Comment by richard-stafflink** [comment]
This works:
```
{ {
  head: {
    text: @l
  },
  body: [
    {
      type: 'message',
      text: @m
    },
    {
      type: 'message',
      text: @t
    },
    {
      type: 'message',
      text: tostring(@i)
    },
    {
      type: 'message',
      text: concat('https://seq.stafflink.io/#/events?filter=@Id', tostring(@i))
    }
  ]
} }
```

![image](https://user-images.githubusercontent.com/106497642/202062768-4c442984-d96a-4849-aa0e-83f903aef781.png)

But @seqid does not:
```
{ {
  head: {
    text: @l
  },
  body: [
    {
      type: 'message',
      text: @m
    },
    {
      type: 'message',
      text: @t
    },
    {
      type: 'message',
      text: tostring(@seqid)
      // OR even: `text: @seqid`
    },
    {
      type: 'message',
      text: concat('https://seq.stafflink.io/#/events?filter=@Id', tostring(@seqid))
    }
  ]
} }
```

**Comment by richard-stafflink** [comment]
I've been referencing these tests for valid template syntax: https://github.com/datalust/seq-app-httprequest/blob/05d407eed937440acd196b2b82df8d139b6c46c6/test/Seq.App.HttpRequest.Tests/Cases/expression-evaluation-cases.asv

**Comment by richard-stafflink** [comment]
`typeof(@seqid)` returns `undefined`

**Comment by richard-stafflink** [comment]
OK, got it working, I had to use `@p['@seqid']`

**Comment by richard-stafflink** [comment]
The full App solution is:
```
{
  "Url": "https://inbots.zoom.us/incoming/hook/XXXXXXXXX?format=full",
  "Method": "POST",
  "Body": "{ {\n  head: {\n    text: @l\n  },\n  body: [\n    {\n      type: 'message',\n      text: @m\n    },\n    {\n      type: 'message',\n      text: @t\n    },\n    {\n      type: 'message',\n      text: 'open log in Seq',\n      link: concat('https://seq.stafflink.io/#/events?filter=@Id%20%3D%20''', @p['@seqid'], '''')\n    }\n  ]\n} }",
  "BodyIsTemplate": "True",
  "MediaType": "application/json",
  "AuthenticationHeader": "[seq-preserve]",
  "OtherHeaders": "",
  "ExtendedErrorDiagnostics": "False"
}
```

The formatted template is:
```
{ {
  head: {
    text: @l
  },
  body: [
    {
      type: 'message',
      text: @m
    },
    {
      type: 'message',
      text: @t
    },
    {
      type: 'message',
      text: 'open log in Seq',
      link: concat('https://seq.stafflink.io/#/events?filter=@Id%20%3D%20''', @p['@seqid'], '''')
    }
  ]
} }
```

**Comment by nblumhardt** [comment]
🙌
